### ISSUE TITLE
Windows OpenTK Maui

### ISSUE THREAD

**Issue by mludlum** [ibluesun/MauiOpenGL#1]
Any progress working on the windows version of this demo?

**Comment by ibluesun** [comment]
wow .. I've been too busy  actually  ..  but in another issue on MAUI  .. there was this solution about getting special OpenGL ES dll that is compatible with WinUI 3.0  found on that link

https://github.com/dotnet/maui/discussions/7758#discussioncomment-6861873  

and I was actually going to investigate it .. but got distracted with life :)

**Comment by mludlum** [comment]
I've been trying to find a cross platform UI framework that also supports 3D graphics bindings and getting this to work is the closest I could find.  Also trying Blazor web extensions with webgl2 but I fear that will be dog slow.

**Comment by gmgallo** [comment]
I second the request to have a bridge control that allows to display an OpenGL window in a WinUI3 desktop app.

**Comment by ibluesun** [comment]
well .. this reminds me that I haven't completed all my attempts yet :)

**Comment by ibluesun** [comment]
ok .. the windows part is now working :)   .. using the patched ANGLE dlls.

**Comment by mludlum** [comment]
Seems to work.  Thanks!  I need to use VAOs.  I was able to run the demo by replacing ES20 with ES30.  Is it as simple as that?

**Comment by ibluesun** [comment]
Pay attention to the Windows\MauiOpenGLHandler.cs   

GL.LoadBinding(..    is actually coming from the namespace at the top using OpenTK.Graphics.ES20;


so I guess you need to change it to ES30  

also I am not sure if this is required .. because sometimes the shader compilers are forgiving  ..  however the context selection on the windows  in  AngleSwapChain.cs  in InitializeContext function is set to use  Context version 2  ..   you may want to change it to 3  if required  

needless to say  on the android part  AndroidOpenGLView.cs   SetEGLContextClientVersion(..) is the one you need.

**Comment by gmgallo** [comment]
The way around I find to host OpenGL in WinUI3 is to grab the underlying HWND handle of WidowCore and create a child Win32 window for it with CreateWindowEx() that can then be overlay over a WinUI3 Border or GRID control. If someone wants to know the implementation details send me a note.

**Comment by ibluesun** [comment]
@gmgallo    but this way you are escaping WinUI3  and getting back into the Win32 API  .. what would be the benefit of such a road if you can  use the patched ANGLE DLL they way it used in this project ?!!

**Comment by gmgallo** [comment]
You are right, I admit that it is a quick and dirty solution, and I should learn about what ANGLE is and see how well it performs in the Windows - intel platform towards what I´m programming, but I'm pressed for time and needed a solution pronto. 

On the positive side, I´m cutting through layers of indirection and using the out of the box OpenGL libraries to work in the way they were originally designed, which should benefit performance. My application deals with high resolution images that must be displayed in real time, so, performance is high in the list.
